### ISSUE TITLE
Site not remembering language settings

### ISSUE THREAD

**Issue by RaenonX** [RaenonX-PokemonSleep/pokemon-sleep-ui#693] opened 2024-01-19 08:07 UTC
https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/10672193/3b757fc3-df20-4bd5-840e-c985084f5b1b

Device: Google Pixel 6
OS: Android 14 (newest update)
Browser: Chrome (newest update)

**Comment by johnmgrant** [comment] 2024-01-20 00:30
So I was able to recreate this. Here are the steps:
1. Navigate to the site
2. Ensure user is signed in
3. Install via PWA (simple share & add to home screen for iOS)
4. After opening the PWA, change the language 
  * Note that the error is not reproducible so long as the user is only using the PWA from this point forward
5. Navigate back to chrome with the prior browser session and either reload the page or navigate to a new link from the previously changed locale
6. Notice that the page is still in the previous language since the path is set explicitly to that locale (`/de/`, `/en/`, etc.).
7. Navigate back to the PWA and notice that the previously set language is still in use.

Some items to note:
* Hard closing the PWA before step 5. will result in the same language set in the browser to be reflected in the PWA.
* Closing the browser session and navigating to the root path of the site at step 5 results in the language change taking place

Steps to resolve this are to either to:
* redirect all future browser page requests to the PWA (if possible?)
* change the start_url of the PWA to be the locale redirect path
* persist language settings separately from website in PWA
* have a redirect in place to route the user to the most recently set local regardless of path they're visiting (not ideal)

<a href="https://drive.google.com/file/d/1aTg78-u7ojAB_mUaoSp5-hyTqn-4Uaxy/preview">Reproduction Video</a>

**Comment by johnmgrant** [comment] 2024-01-20 00:59
Looks like I'lll resolve this by removing the redirect caching.

**Comment by RaenonX** [comment] 2024-01-20 13:39
Doesn't seem to be fixed according to the reporter

**Comment by johnmgrant** [comment] 2024-01-20 13:42
User reports that the language in the PWA defaults to system language after the following steps are followed:

1. Delete the existing PWA
2. Visit the website in chrome on affected device
3. Change the language to desired language for site 
4. Install progressive web app to Home Screen
5. See if language persists

**Comment by johnmgrant** [comment] 2024-01-25 17:55
After further discussion, it sounds like the issue is as follows:

The user has a default language for devices is one thing (say German), but it would like for any language override made to the site setting to persist for all future site visits on all devices where the user is logged in.

As such, I will be breaking out the changes in #716 and address this change in a new pull request.

**Closed** 2024-01-31 22:00 UTC
Labels: bug
